---

# all:
#   vars:
#     admin_email: "admin@example.com"
#     cloudflare_email: "admin@example.com"
#     cloudflare_api_key: "c02b7d24a066adb747fdeb12deb21bfa"

#   hosts:
#     test.example.com:
#       ansible_host: "203.0.113.10"
#       ansible_user: "ansible"
#       sites:
#         - { server_name: ["example.com", "*.example.com"], cloudflare_zone: "example.com" }
#         - { server_name: ["staging.example.com"],
#             force: True,
#             staging: True,
#             proxy_port: 8080, 
#             basic_auth_user: "test", 
#             basic_auth_pass: "test" }

#   children:
#     bootstrap:
#       hosts:
#         test.example.com:
#     stack:
#       hosts:
#         test.example.com:
#     vhost:
#       hosts:
#         test.example.com:
