---

- name: "Request Let's Encrypt Certificate (Webroot)"
  command: "certbot certonly --server='{{letsencrypt_directory}}' --webroot -d {{server_name|join(' -d ')}}"
  when: cloudflare_zone == None

- name: "Request Let's Encrypt Certificate (Cloudflare)"
  command: "certbot certonly --server='{{letsencrypt_directory}}' --dns-cloudflare -d {{server_name|join(' -d ')}}"
  when: cloudflare_zone == None
