---

- name: "Assign Site Vars"
  set_fact:
    basic_auth_pass: "{{site.basic_auth_pass|default('')}}"
    basic_auth_realm: "{{site.basic_auth_realm|default('Restricted')}}"
    basic_auth_user: "{{site.basic_auth_user|default('')}}"
    cloudflare: "{{site.cloudflare|default(False)}}"
    cloudflare_zone: "{{site.cloudflare_zone|default(None)}}"
    letsencrypt_force_renewal: "{{site.force|default(False)}}"
    nginx_force_override: "{{site.force|default(False)}}"
    nginx_site_root: "{{site_root|default('/var/www/{{server_name[0]}}')}}"
    proxy_host: "{{site.proxy_host|default('http://127.0.0.1')}}"
    proxy_port: "{{site.proxy_port|default('')}}"
    server_name: "{{site.server_name}}"
    staging: "{{site.staging|default(False)}}"

- name: "Set ACME Directory"
  set_fact:
    letsencrypt_directory: "{{letsencrypt_directory_staging}}"
  when: staging == True
