---

- name: "Install Packages"
  apt:
    name: "{{packages}}"
    update_cache: yes
  vars:
    packages:
      - postfix
      - mailutils

- name: "Add Postfix Null Client Config"
  template:
    src: "main.cf.j2"
    dest: "/etc/postfix/main.cf"
    force: yes

- name: "Remove Existing Root Alias"
  lineinfile:
    path: "/etc/aliases"
    regexp: '^root'
    state: absent

- name: "Add Root Alias Email Address"
  lineinfile:
    path: "/etc/aliases"
    line: "root: {{admin_email}}"
  when: admin_email is defined

- name: "Refresh Alias DB"
  command: "newaliases"
  when: admin_email is defined

- name: "Restart Postfix Service"
  service:
    name: "postfix"
    state: restarted
