---

- name: "Install Certbot"
  apt:
    name: "{{packages}}"
    update_cache: yes
  vars:
    packages:
      - python3-certbot
      - python3-certbot-dns-cloudflare

- name: "Create Let's Encrypt Directories"
  file:
    path: "{{item}}"
    state: directory
  with_items:
    - "{{letsencrypt_challenge_root}}/.well-known/acme-challenge"
    - "/etc/letsencrypt/renewal-hooks/deploy"

- name: "Add Renewal Hook"
  copy:
    src: "renewal-hook"
    dest: "/etc/letsencrypt/renewal-hooks/deploy/nginx"

- name: "Copy cli.ini"
  template:
    src: "cli.ini.j2"
    dest: "/etc/letsencrypt/cli.ini"

- name: "Copy cloudflare.ini"
  template:
    src: "cloudflare.ini.j2"
    dest: "/etc/letsencrypt/cloudflare.ini"
    mode: 0400
    owner: "root"
    group: "root"
  when: cloudflare_email is defined and cloudflare_api_key is defined
