---

- name: "Add iptables Rules (Debian)"
  block:
    - name: "Allow Mosh Ports"
      iptables:
        chain: INPUT
        protocol: udp
        destination_port: "60000:61000"
        jump: ACCEPT
    
    - name: "Make Firewall Rules Persistent"
      shell: "iptables-save > /etc/iptables/rules.v4"
  when: ansible_distribution == "Debian"

- name: "Add ufw Rules (Ubuntu)"
  block:
    - name: "Allow Mosh Ports"
      ufw:
        rule: allow
        proto: udp
        port: "60000:61000"
  when: ansible_distribution == "Ubuntu"


