---

- name: "Add Docker Signing Keys"
  apt_key:
    url: "https://download.docker.com/linux/{{ansible_distribution|lower}}/gpg"

- name: "Add Docker Repository"
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"
    filename: "docker"
    update_cache: yes

- name: "Install Docker"
  apt:
    name: "docker"
    update_cache: yes

- name: "Install docker-compose"
  pip:
    name: "docker-compose"
